databases:
  - name: jcmcsite
    databaseName: jcmcsite
    user: jcmcsite

services:
  - type: web
    name: jcmcsite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jcmcsite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4