# Generated by Django 3.2 on 2023-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your e-mail address')),
                ('github', models.URLField(verbose_name='Your GitHub profile URL')),
            ],
        ),
    ]
