# Generated by Django 3.2 on 2023-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='gender',
            field=models.CharField(choices=[('SELECT', 'Please Choose'), ('WOMAN', 'Woman'), ('MAN', 'Man'), ('NONBINARY', 'Non-binary'), ('FLUID', 'Gender Fluid'), ('TRANS', 'Transgender'), ('NOTSAY', 'Prefer not to say')], default='SELECT', max_length=9),
        ),
    ]
