# Generated by Django 3.2 on 2023-12-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_uploadmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='pylint_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
