# Generated by Django 3.2 on 2023-12-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_uploadmodel_pylint_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='pylint_score',
        ),
    ]
