# Generated by Django 3.2 on 2023-12-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_remove_uploadmodel_pylint_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='pylint_score',
            field=models.CharField(max_length=100, null=True, verbose_name='Pylint score'),
        ),
    ]
