# Generated by Django 3.2 on 2023-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_uploadmodel_pylint_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='components',
            field=models.CharField(max_length=100, null=True, verbose_name='Components'),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='gender_guess',
            field=models.CharField(max_length=100, null=True, verbose_name='Gender Guess'),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='gender_guess_probs',
            field=models.CharField(max_length=100, null=True, verbose_name='Gender Guess Probablity'),
        ),
    ]
