# Generated by Django 3.2 on 2023-12-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_auto_20231205_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='gender_guess_probs',
            new_name='gender_guess_proba',
        ),
    ]
