# Generated by Django 3.2 on 2023-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0007_rename_gender_guess_probs_uploadmodel_gender_guess_proba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='components',
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='email',
            field=models.EmailField(max_length=1000, verbose_name='Your e-mail address'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='gender_guess',
            field=models.CharField(max_length=1000, null=True, verbose_name='Gender Guess'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='gender_guess_proba',
            field=models.CharField(max_length=1000, null=True, verbose_name='Gender Guess Probability'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='github',
            field=models.URLField(max_length=1000, verbose_name='Your GitHub profile URL'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Your full name'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='pylint_score',
            field=models.CharField(max_length=1000, null=True, verbose_name='Pylint score'),
        ),
    ]
